spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
      s3:
        bucket: ${S3_BUCKET_NAME}

app:
  jwt:
    secret: ${JWT_SECRET_KEY}  # 최소 32byte 이상
    expiration-millis: 3600000 # 1시간

logging:
  level:
    root: info
    org.springframework.web: debug                       # 들어온 API 요청 로그
    org.springframework.web.servlet.DispatcherServlet: debug # 요청/응답 상태 로그
    org.hibernate.SQL: debug                             # 실행되는 SQL 로그
    org.hibernate.type.descriptor.sql.BasicBinder: trace # SQL 파라미터 값까지 출력
    reactor.netty.http.client: debug                     # WebClient 외부 API 호출 로그