spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # Hibernate drop 동작 차단
    properties:
      # 표준 JPA 스키마 생성 옵션
      jakarta.persistence.schema-generation.database.action: create
      jakarta.persistence.schema-generation.create-source: metadata
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
      s3:
        bucket: ${S3_BUCKET_NAME}

app:
  jwt:
    secret: ${JWT_SECRET_KEY}  # 최소 32byte 이상
    expiration-millis: 3600000 # 1시간