name: π’΅ Feature
description: μƒλ΅μ΄ κΈ°λ¥ μ¶”κ°€
title: "[Feature]: "
labels:
  - π’΅ Feature
projects: ["dnd-side-project/119"]
body:
  - type: textarea
    attributes:
      label: π“„ μ„¤λ…
      placeholder: μμ„Έν μ μ„μλ΅ μΆ‹μµλ‹λ‹¤!
    validations:
      required: true
  - type: textarea
    attributes:
      label: β”οΈ μ‘μ—…ν•  λ‚΄μ©
      placeholder: |
        - [ ] μ‘μ—… 1: μ—”λ“ν¬μΈνΈ μ—°λ™
        - [ ] μ‘μ—… 2: λ¦¬μ¤ν°μ¤ DTO μ‘μ„±
        μµλ€ν• μμ„Έν μ μ–΄μ£Όμ„Έμ”!
    validations:
      required: false
